
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS"
export const ADD_ITEM_FAILURE = "ADD_ITEM_FAILURE"
export const ADD_ITEM_REQUEST = "ADD_ITEM_REQUEST"

export const GET_ITEM_SUCCESS = "GET_ITEM_SUCCESS"
export const GET_ITEM_FAILURE = "GET_ITEM_FAILURE"
export const GET_ITEM_REQUEST = "GET_ITEM_REQUEST"

export const REMOVE_ITEM_SUCCESS = "REMOVE_ITEM_SUCCESS"
export const REMOVE_ITEM_FAILURE = "REMOVE_ITEM_FAILURE"
export const REMOVE_ITEM_REQUEST = "REMOVE_ITEM_REQUEST"

export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS"
export const UPDATE_ITEM_FAILURE = "UPDATE_ITEM_FAILURE"
export const UPDATE_ITEM_REQUEST = "UPDATE_ITEM_REQUEST"